package view.com.raven.component;

import com.raven.controller.ControllerClientes;
import com.raven.controller.ControllerRefeicoes;
import com.raven.controller.ControllerRelatorios;
import com.raven.controller.ControllerSenha;
import com.raven.dao.RelatoriosDao;
import com.raven.model.Refeicoes;
import com.raven.model.Relatorios;
import com.raven.model.Senha;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.io.FileNotFoundException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showInputDialog;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import view.com.raven.swing.ScrollBar;

public class CardExpediente extends javax.swing.JPanel {

    String data2;

    ControllerSenha controllerSenha = new ControllerSenha();
    ControllerRefeicoes controllerRefeicoes = new ControllerRefeicoes();
    ControllerRelatorios controllerRelatorios = new ControllerRelatorios();
    ControllerClientes controllerClientes = new ControllerClientes();

    Refeicoes refeicoes = new Refeicoes();
    Relatorios relatorios = new Relatorios();

    RelatoriosDao relatoriosDao = new RelatoriosDao();

    ArrayList<Senha> listSenha = new ArrayList<>();

    public CardExpediente() {
        initComponents();
        txtData_refeicao.setVisible(false);
        setOpaque(false);
        tabela_senha();

        // A  linha Abaixo exibe a Data Atual do Sistema.
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();

    }

    //LISTAR SENHAS NA TABELA
    public final void tabela_senha() {
        spTableSenhas.setVerticalScrollBar(new ScrollBar());
        spTableSenhas.getVerticalScrollBar().setBackground(Color.WHITE);
        spTableSenhas.getViewport().setBackground(Color.WHITE);

        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        spTableSenhas.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);

        listSenha = controllerSenha.returnListSenhaController();
        DefaultTableModel table = (DefaultTableModel) table_Senhas.getModel();
        table.setNumRows(0);
        //Inserir dados na tabela
        int cont = listSenha.size();
        for (int i = 0; i < cont; i++) {
            table.addRow(new Object[]{
                listSenha.get(i).getId(),
                listSenha.get(i).getCliente(),
                listSenha.get(i).getIdade(),
                listSenha.get(i).getGenero(),
                listSenha.get(i).getTipoSenha(),
                listSenha.get(i).getData_refeicao()
            });
        }
    }//FIM.

    //LIMPAR CAMPOS
    public void limparCampos() {
        txtCardapio.setText("");
        txtInicioSenhas.setText("");
        txt_terminoSenhas.setText("");
        txt_terminoDistribuicao.setText("");
        txt_ocorrencia.setText("");
    }//FIM.

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        spTableSenhas = new javax.swing.JScrollPane();
        table_Senhas = new view.com.raven.swing.Table2();
        jLabel6 = new javax.swing.JLabel();
        btnSenhasGeradas = new javax.swing.JButton();
        btnFecharDia = new javax.swing.JButton();
        txtData_refeicao = new javax.swing.JLabel();
        txtCardapio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_ocorrencia = new javax.swing.JTextArea();
        txtInicioSenhas = new javax.swing.JFormattedTextField();
        txt_terminoSenhas = new javax.swing.JFormattedTextField();
        txt_terminoDistribuicao = new javax.swing.JFormattedTextField();

        setPreferredSize(new java.awt.Dimension(1142, 622));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("INÍCIO DAS SENHAS:");

        spTableSenhas.setBorder(null);

        table_Senhas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SENHA", "NOME", "IDADE", "GENERO", "TIPO SENHA", "DATA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_Senhas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_SenhasMouseClicked(evt);
            }
        });
        spTableSenhas.setViewportView(table_Senhas);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CARDÁPIO:");

        btnSenhasGeradas.setText("SENHAS GERADAS");
        btnSenhasGeradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSenhasGeradasActionPerformed(evt);
            }
        });

        btnFecharDia.setText("FECHAR O DIA");
        btnFecharDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharDiaActionPerformed(evt);
            }
        });

        txtCardapio.setDisabledTextColor(new java.awt.Color(187, 187, 187));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TÉRMINO DAS SENHAS:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TÉRMINO DA DISTRIBUIÇÃO:");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("OCORRÊNCIAS:");

        txt_ocorrencia.setColumns(20);
        txt_ocorrencia.setRows(5);
        jScrollPane1.setViewportView(txt_ocorrencia);

        try {
            txtInicioSenhas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txt_terminoSenhas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txt_terminoDistribuicao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(txtData_refeicao, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spTableSenhas, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_terminoDistribuicao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                .addComponent(txt_terminoSenhas, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtInicioSenhas, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCardapio, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSenhasGeradas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFecharDia, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(235, 235, 235))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtData_refeicao, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSenhasGeradas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFecharDia))
                    .addComponent(spTableSenhas, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCardapio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInicioSenhas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_terminoSenhas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_terminoDistribuicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void table_SenhasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_SenhasMouseClicked
    }//GEN-LAST:event_table_SenhasMouseClicked

    private void btnSenhasGeradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSenhasGeradasActionPerformed
        tabela_senha();
    }//GEN-LAST:event_btnSenhasGeradasActionPerformed

    private void btnFecharDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharDiaActionPerformed

        String resultado = JOptionPane.showInputDialog(null, "Insira uma senha de Administrador para encerrar o expediente.");

        //VERIFICAÇÃO DE SENHA DE ADMINISTRADOR PARA FECHAR O SISTEMA.
        if (controllerSenha.controlChecarSenha(resultado) == 1) {
            //RECEBENDO TOTAL DE REFEIÇÕES SERVIDAS E JOGANDO O VALOR PARA UMA VARIÁVEL LOCAL RECEBER O VALOR.
            String totalServido = JOptionPane.showInputDialog(null, "Insira o total de refeições servidas.");
            //CAMPOS PARA GERAR RELATÓRIO
            String ocorr
                    = "Cardápio: " + txtCardapio.getText().toString().toUpperCase()
                    + "\n Início das senhas: " + txtInicioSenhas.getText().toString().toUpperCase()
                    + "\n Término das senhas: " + txt_terminoSenhas.getText().toString().toUpperCase()
                    + "\n Término da distribuição: " + txt_terminoDistribuicao.getText().toString().toUpperCase()
                    + "\n Ocorrências: " + txt_ocorrencia.getText().toString().toUpperCase();

            //PEGANDO VALOR DA VARIÁVEL "totalServido", E PASSANDO COMO PARÂMETRO PARA SALVAR NA TABELA "tb_refeicoes_vendidas".
            refeicoes.setTotal_servido(Integer.parseInt(totalServido));

            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            Date date = new Date();

            refeicoes.setData(dateFormat.format(date));//DATA SENDO PASSADA PARA SER SALVA NA TABELA CITADA ACIMA.
            boolean result = controllerRefeicoes.controlSaveRefeicoes(refeicoes);// PASSANDO VALORES PARA O BACK-END PARA SALVAR.
            //
            if (result == true && !totalServido.toString().equalsIgnoreCase("")) {
                //PASSANDO OS DADOS DOS RELATORIOS COMO PARAMETROS PARA SEREM LIDOS NO METODO "lerParaOBL" DA CLASSE RelatoriosDAO.
                controllerRelatorios.controlLerOBL(relatorios);
                if (controllerRelatorios.controlSaveRelatorios(relatorios)) {//PASSANDO DADOS PARA O BACK-END, PARA SEREM SALVOS NA TABELA "tb_relatorios".
                    //LIMPAR TABELA AO SALVAR E FECHAR O DIA. 
                    DefaultTableModel table = (DefaultTableModel) table_Senhas.getModel();
                    table.setNumRows(0);
                    JOptionPane.showMessageDialog(null, "Expediente encerrado!", "Mensagem", JOptionPane.PLAIN_MESSAGE);
                    //LIMPAR CAMPOS DE RELATORIOS.
                    limparCampos();

                    try {
                        relatoriosDao.escreverNoRELATORIOPDF(relatoriosDao.lerRelatorios(dateFormat.format(date), ocorr));
                        controllerSenha.controlLimparSenhas();
                        controllerClientes.controlLimparResumodia();
                    } catch (FileNotFoundException e1) {
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Você já encerrou o expediente hoje!", "Mensagem", JOptionPane.PLAIN_MESSAGE);
                }//FIM DA CONDIÇÃO SALVAR RELATORIO

            } else {
                JOptionPane.showMessageDialog(this, "Erro ao Salvar Expediente!");
                limparCampos();
            }

        } else {
            JOptionPane.showMessageDialog(null, "Senha de administrador não confere!", "Mensagem", JOptionPane.PLAIN_MESSAGE);
        } //FIM DA CONDIÇÃO PARA VERIFICAR SENHA.
    }//GEN-LAST:event_btnFecharDiaActionPerformed

    @Override
    protected void paintChildren(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint g = new GradientPaint(0, 0, Color.decode("#1CB5E0"), 0, getHeight(), Color.decode("#000046"));
        g2.setPaint(g);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        g2.fillRect(getWidth() - 20, 0, getWidth(), getHeight());
        super.paintChildren(grphcs);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFecharDia;
    private javax.swing.JButton btnSenhasGeradas;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane spTableSenhas;
    private view.com.raven.swing.Table2 table_Senhas;
    private javax.swing.JTextField txtCardapio;
    private javax.swing.JLabel txtData_refeicao;
    private javax.swing.JFormattedTextField txtInicioSenhas;
    private javax.swing.JTextArea txt_ocorrencia;
    private javax.swing.JFormattedTextField txt_terminoDistribuicao;
    private javax.swing.JFormattedTextField txt_terminoSenhas;
    // End of variables declaration//GEN-END:variables
}
