package view.com.raven.main;

//import com.raven.event.EventMenuSelected;
import com.raven.banco.ConexaoBD;
import view.com.raven.form.Form_Home;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import view.com.raven.event.EventMenuSelected;
import java.sql.Timestamp;
import view.com.raven.form.Form_Funcionarios;
import view.com.raven.form.Form_Clientes;
import view.com.raven.form.Form_Vendas;
import view.com.raven.form.Form_ExpeSenhas;
import view.com.login.TelaLogin;

/**
 *
 * @author RAVEN
 */
public class Main extends javax.swing.JFrame {

    private Form_Home home;

    private Form_Funcionarios formFuncionarios;

//    private Form_Clientes formClientes;
//
//    private Form_Vendas formVendas;
//
//    private Form_ExpeSenhas form_ExpeSenhas;
//
    private TelaLogin telaLogin;

    int codUser;

    public String usuário;

    ConexaoBD con = new ConexaoBD();

    public Main() {
        initComponents();
        lbusuarios.setVisible(false);
        con.getConectar();
        setBackground(new Color(0, 0, 0, 0));

        home = new Form_Home();

        formFuncionarios = new Form_Funcionarios();

//        formClientes = new Form_Clientes();
//
//        formVendas = new Form_Vendas();
//
//        form_ExpeSenhas = new Form_ExpeSenhas();
//
        telaLogin = new TelaLogin();
        menu1.initMoving(Main.this);

        menu1.addEventMenuSelected(new EventMenuSelected() {
            @Override
            public void selected(int index) {
                switch (index) {
                    case 0:
                        setForm(home);
                        break;
                    case 1:
                        CheckLogin();
                        break;
                    case 2:
//                        setForm(formClientes);
                        break;
                    case 4:
//                        setForm(formVendas);
                        break;
                    case 5:
//                        setForm(form_ExpeSenhas);
                        break;
                    case 6:
                        int res = 0;
                        res = JOptionPane.showConfirmDialog(rootPane, "Deseja Trocar de Usuário?");
                        if (res == JOptionPane.YES_OPTION) {
                            trocarUsuario();
                            con.getfecharConexao();
                        }
                        break;
                    case 7:
                        int resposta = 0;
                        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente sair do sistema?");
                        if (resposta == JOptionPane.YES_OPTION) {
                            System.exit(0);
                            con.getfecharConexao();
                        }
                        break;
                    default:
                        break;
                }
            }
        });
        //  set when system open start with home form
        setForm(new Form_Home());
    }

    private void CheckLogin() {
        try {
            Form_Funcionarios funcionarios = new Form_Funcionarios();
            con.executarSql("select*from admins where cpf_admin='" + lbusuarios.getText() + "'");
            con.getResultSet().first();
            if (con.getResultSet().getString("cargo_admin").equals("Administrador")) {
                if (funcionarios == funcionarios) {
                    setForm(funcionarios);
                    funcionarios.setVisible(true);
                } else {
                    funcionarios.setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Você não tem Acesso a essa Funcionalidade!\n Contate o Administrador do Sistema!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Você não tem Acesso a essa Funcionalidade!\n Contate o Administrador do Sistema!" + ex.getMessage());
        }
    }

    private void trocarUsuario() {
        telaLogin.setVisible(true);
        dispose();
    }

    private void setForm(JComponent com) {
        mainPanel.removeAll();
        mainPanel.add(com);
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new view.com.raven.swing.PanelBorder();
        header2 = new view.com.raven.component.Header();
        mainPanel = new javax.swing.JPanel();
        lbusuarios = new javax.swing.JLabel();
        menu1 = new view.com.raven.component.Menu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        panelBorder1.setBackground(new java.awt.Color(242, 238, 238));

        header2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        mainPanel.setOpaque(false);
        mainPanel.setLayout(new java.awt.BorderLayout());

        lbusuarios.setEnabled(false);

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1095, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(lbusuarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(header2, javax.swing.GroupLayout.PREFERRED_SIZE, 1095, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(menu1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        lbusuarios.setText(usuário);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Long datetime = System.currentTimeMillis();
        Timestamp timestamp = new Timestamp(datetime);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.com.raven.component.Header header2;
    private javax.swing.JLabel lbusuarios;
    private javax.swing.JPanel mainPanel;
    private view.com.raven.component.Menu menu1;
    private view.com.raven.swing.PanelBorder panelBorder1;
    // End of variables declaration//GEN-END:variables
}
